### ISSUE TITLE
Diagrama

### ISSUE THREAD

**Issue by DuilioAquino10** [SistemasTecTlaxiaco/practica-de-diagrama-de-secuencia-team-pro#1]
[Practica secuencia.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-diagrama-de-secuencia-team-pro/files/7819686/Practica.secuencia.pdf)

**Comment by IsraelNicolas61** [comment]
Calificación: 29%

**Comment by josealfredo79** [comment]
En el diagrama en los mensajes o métodos hace falta los parametros..

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado
